= All Things Wood

A collection of information regarding wood and working with it.

== Wood glues

Certainly, there are many ways of joining different pieces of wood together, but
using glue is one of the most common ways to do so. However, there is a wide
variety of glues that can be used.

=== Synthetic glues
Synthetic glues are the most commonly used today because they usually offer some
advantages compared to natural glues that have been used traditionally, such as
higher adhesive strength, easier application or complete resistance to moisture,
which can greatly simplify construction in outdoor applications, for instance.

==== PVA glue
Likely one of the most widely used glues, PVA (polyvinyl acetate) glue,
also known as "white glue" or the yellow "carpenter's glue", is a proven glue
that is popular due to it's wide availability and low cost. PVA glue is usually
a dispersion of PVA in water. Once applied, the water will slowly evaporate and
drawn into the wood, causing the glue to harden and the joined wood surfaces to
adhere to each other. As any material, however, PVA glue has it's limits.

Generally, the instructions of the particular PVA glue that was bought are what
is valid for that specific product. However, PVA glues are normally very similar
in some aspects:

[horizontal]
Working temperature:: 8°C to ~40°C +
                      (ideally between 15°C and 25°C)
Processing time:: 5 to 10 minutes +
                  (can be extended by thinning with water to an extent)
Clamping time:: no less than 20 minutes
Max. temperature:: about 60°C
Storage temperature:: 0°C - 30°C
Water resistant:: no
Shelf life:: up to about 6 months

PVA glue will saponify easily under alkaline conditions and is very susceptible
to solvents, which will make the glue joint fail very easily. This may make it
impossible to use certain wood stains, paints or wood finishes. Despite these
limitations, PVA glue is a very good wood glue and is a good choice for most
indoor applications.

If it is not clear whether or not the product in question is compatible with
PVA glue, it is always advisable to test it with two small pieces of scrap wood.
