== Wood finishes

Wood finishes are applied to the work piece to protect the wood against
environmental influences, make it more resistant to wear or deterioration.
Usually the finishes are applied after assembly, especially in furniture making.
There are cases when they are applied before the wood is used in it's final
function though.

There is a wide variety of wood finishes available. Many products are blends of
components that could be used on their own as well. A list of commonly available
finishes, their properties and a couple of recipes for homemade finishes can be
found below.

=== Lacquer
Lacquer for wood, today, typically consists of a blend of synthetic polymers. It
is a rather durable coating for wood and can either be transparent, in which
case it is often applied after staining the wood, or it can contain pigments to
give it color and hide the wood surface. The lacquer is usually dissolved in
mineral spirits and dries quickly.

The wood surface is pretty much sealed after applying lacquer, so the wood will
no longer exchange moisture with the surrounding air. Additionally, if there is
a crack in the surface, moisture can enter the wood through it. However, the
wood cannot properly dry anymore, which can cause mold to grow and destroy the
wood from the inside, making lacquer a poor choice for some applications.

=== Shellac
Shellac is a natural resin produced by the lac bug. On it's own, Shellac is very
brittle at room temperature, so depending on the application, it is blended with
with, for instance, drying oils. For application, it is dissolved in ethanol or
isopropyl alcohol. Mineral spirits also work and may be necessary for some
blends.

It's color can be either white (bleached), amber or deep red-brown, which is why
it is sometimes used as a wood stain and then coated with a different wood
finishes.

When exposed to water, shellac will well up and therefore is not waterproof.

=== Drying oils
Drying oils are oils that will naturally polymerize by absorbing oxygen from the
air over time. The term "curing" would be more accurate, but is uncommon.
Sometimes a drying agent is added or the oil is pre-polymerized and then thinned
to accelerate the curing time, though neither is strictly necessary.

Oils are normally applied more than once to achieve a sufficient coat. How often
depends on various factors, such as how much the oil was thinned (if at all) and
if it was treated to accelerate curing time, as well as the desired protection,
look and feel of the wood.

An important property of drying oils is that they are hydrophobic, meaning
liquid water will not wet the surface of wood treated with it easily, but they
are not impermeable to water vapor. Due to this, the wood will still absorb and
release moisture from the environment. This is why furniture that is only
treated with drying oils helps regulate the indoor climate, leading to generally
higher comfort.

After the first applied layer of oil has dried to the point where the surface
will not release any oil anymore if it is touched, the wood should be sanded.
Sandpaper in the 120 grit to 320 grit range at most should be used to allow oil
to still easily pass through the surface. Any sanding dust should be removed
before the next oil coat or use of a different wood finish on top.

Untreated drying oils penetrate very deep into the wood and achieve a thick
protective layer, given several applications of oil.

==== Linseed oil
Linseed oil is the most widely known and available type of drying oil. After
drying, the oil will stay somewhat flexible and can deal very well with
mechanical stresses and expansion/contraction of the wood due to varying
moisture or temperature.

Linseed oil for use as wood finish is most commonly sold as Boiled Linseed Oil
(BLO), typically also with drying agents, which allows further treatment of the
wood surface after just 24 hours of curing time at room temperature. Untreated
linseed oil will need several days to a week before it has sufficiently cured so
a second coat can be applied.

It can be used to help preserve furniture and structural wood in outdoor
application, although it will degenerate over time when exposed to UV light.
Window frames preserved with linseed oil should get a new oil coat every 1 to 5
years, depending on the intensity of the exposure. The surface must be clean
before application, but sanding is not necessary for a "refresh coat".

This problem can be alleviated, although not eliminated, by using pigments in
the topmost oil layers, but doing so will make the natural wood structure
invisible.
